"""add soft delete for expense model

Revision ID: 6b115a659aa4
Revises: db4df09cbc43
Create Date: 2026-05-11 04:49:46.177196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b115a659aa4'
down_revision: Union[str, Sequence[str], None] = 'db4df09cbc43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses', 'is_deleted')
    # ### end Alembic commands ###
